name:                gloss-random
version:             0.1.0.0
github:              "scriptocreator/gloss-random"
license:             BSD-3-Clause
author:              Andrey Boyarkin
maintainer:          andrey.boyarkin1999@gmail.com
copyright:           "2024 Andrey Boyarkin"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Game

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/scriptocreator/gloss-random#readme>

dependencies:
- base >= 4.7 && < 5
- gloss
- random

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  ball-exe:
    main:                Main.hs
    source-dirs:         1-ball
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gloss-random
  screen-exe:
    main:                Main.hs
    source-dirs:         2-screen
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gloss-random
  array-exe:
    main:                Main.hs
    source-dirs:         3-array
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gloss-random
  nesting-exe:
    main:                Main.hs
    source-dirs:         4-nesting
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gloss-random
  substructure-exe:
    main:                Main.hs
    source-dirs:         5-substructure
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gloss-random
  rotation-balls-exe:
    main:                Main.hs
    source-dirs:         6-rotation_balls
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gloss-random
  wheel-exe:
    main:                Main.hs
    source-dirs:         7-wheel
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gloss-random
  rotation-wheels-exe:
    main:                Main.hs
    source-dirs:         8-rotation_wheels
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gloss-random
  rotation-wheel-exe:
    main:                Main.hs
    source-dirs:         9-rotation_wheel
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gloss-random

tests:
  gloss-random-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gloss-random
